### ISSUE TITLE
[Feature Request] Send play_media service request

### ISSUE THREAD

**Issue by ljmerza** [kalkih/mini-media-player#110]
Can you add an input for a media_content_id and dropdown for media_content_type to send a play_media request to the media_extractor?

**Comment by kalkih** [comment]
Don’t think this will be added to the card unfortunately, mostly because it can be achieved fairly easy already thanks to the flexibility of lovelace, an input_text, a button and a script and you’re ready. You could even utilize a mini-media-player shortcut button instead of an extra button to trigger the script.
