### ISSUE TITLE
Volume tooltip cut off

### ISSUE THREAD

**Issue by Mace404** [kalkih/mini-media-player#131]
The volume bar is being cut of if it is on the top row of a card:

![image](https://user-images.githubusercontent.com/41652357/59718970-95697700-921b-11e9-84bb-6398b686464b.png)

Here it is on a different card with some more room:

![image](https://user-images.githubusercontent.com/41652357/59718993-a31efc80-921b-11e9-9cca-08817f9f64a1.png)

Just updated to 1.20 from 0.9.8. Did not have the issue in 0.9.8

**Comment by kalkih** [comment]
Hey,
So I looked into this, and it's caused by the use of the entities card, which now applies the style [`overflow: hidden`](https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/cards/hui-entities-card.ts#L136-L138 ) to child cards, hence why the pin is cut off.

I can override that which should fix the issue.
