### ISSUE TITLE
How to install w/o ui-lovelace.yaml?

### ISSUE THREAD

**Issue by Vendo232** [kalkih/mini-media-player#168]
Can you install this when I use default Lovelace w/o special ui-lovelace.yaml?
I`m using configuration.yaml and I use "Configure UI" to edit my lovelace

**Comment by kalkih** [comment]
Sure, follow the regular install instructions but instead of opening ui-lovelace.yaml to insert the resource reference, go into the raw config editor and do it there.

[Here's](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins) a great guide on how to install cards/plugins in general.

**Comment by nagyrobi** [comment]
How do you split config in that case? For the same repetitive code?
