### ISSUE TITLE
Card is cramped when group=true and corners are rounded

### ISSUE THREAD

**Issue by alexander-bauer** [kalkih/mini-media-player#173]
Hello!

I am using mini-media-player v1.3.1, and want to share the below two screenshots, firstly with `group: true`, and secondly without on both of my mini-media-players (`Sasha's Room` and `Sasha's Corridor`). Other elements in the screenshot are [thomasloven's fold-entity-row card](https://github.com/thomasloven/lovelace-fold-entity-row) and [his slider-entity-row card](https://github.com/thomasloven/lovelace-slider-entity-row).

![Screenshot 2019-09-24 at 8 36 56 AM](https://user-images.githubusercontent.com/1558334/65512648-a32c3980-dea7-11e9-9507-f78576386c1d.png)
**^ with `group: true`**

![Screenshot 2019-09-24 at 8 36 28 AM](https://user-images.githubusercontent.com/1558334/65512664-a58e9380-dea7-11e9-81ca-2e3c55f36032.png)
**^ without**

---

My theme makes use of transparent cards and rounded corners. As you can see in the bottom screenshot, the `Sasha's Corridor` card that's currently idle has slight opacity that makes it stand out in the middle of the list -- that's happily resolved in the above screenshot when `group: true`.

However, the `Sasha's Room` card that's playing is made very cramped by the rounded corners when `group: true` (top). When not (bottom), it's got plenty of room, and stands off the enclosing card anyway because of the cover art, which works great for me.

When a media player is idle, I'd like to have it become more compact and matching, as `group: true` achieves, but still become more prominent and roomy when it's playing. It doesn't seem appropriate to try and make `group` conditionally true, but instead to ask to optionally increase the margins when media is playing.

**Comment by kalkih** [comment]
Hello,

This feels a bit too niché to implement as an card option in my opinion, it can however already be achieved with the help of other plugins.

If you want to conditionally change the group option based on state I recommend checking out [config-template-card](https://github.com/custom-cards/config-template-card) with which you can achieve this.

Another option would be to use [lovelace-card-mod](https://github.com/thomasloven/lovelace-card-mod) to customize the paddings as you like (can also be done conditionally).

**Comment by alexander-bauer** [comment]
Understandable, thank you very much for your work in making this card, and for your prompt reply! I'll be happily using the card with `group: true` as-is, and seeking out more general theme improvements as I can.

**Comment by kalkih** [comment]
Thank you for understanding and for the kind words.

One suggestion would be to play around with the cards [theme variables](https://github.com/kalkih/mini-media-player#theme-variables), specifically the artwork/overlay ones, I think you could make players with artwork blend better with your transparent theme.

`mini-media-player-artwork-opacity`& `mini-media-player-overlay-color`.

Here's an example from one of my room setups, with a similar transparent theme.
Although, the artwork transparency might be a bit too much (bottom card), since you hardly can't see the artwork anymore 😆.

![Screenshot 2019-09-24 at 17 46 14](https://user-images.githubusercontent.com/457678/65527805-96353780-def3-11e9-99e8-8282219719bc.png)
