### ISSUE TITLE
Can’t adjust slider after volume has been turned all the way down

### ISSUE THREAD

**Issue by justin144** [kalkih/mini-media-player#179]
If the volume has been turned all the way down, I’m unable to move the slider. I have to manually make a service call to increase the volume before it will let me adjust the slider again

**Comment by kalkih** [comment]
Need more info,
What media player component does it happen with?
Does it happen in the media player popup as well?
Card setup & config (preferably with a screenshot).
Desktop/mobile?
Browser?

**Comment by kalkih** [comment]
Thanks,
Never seen that behaviour before.
Since it happens in the more info popup as well (which is part of core HA) it might be a bug in the alexa media player component.

Could you please do me a favor? when the volume is at zero and you can't adjust it go to `https://[HA]:[PORT]/developer-tools/state`, select the media player entity in the dropdown and copy paste the state attributes here.

Thanks!

**Comment by justin144** [comment]
Hmm.. yah, you're probably right.  Here are the attributes:

volume_level: 0
is_volume_muted: true
media_content_type: music
media_duration: 269
media_position: 0
media_position_updated_at: 2019-10-16T18:44:35.108291+00:00
media_title: Can't Stop
media_artist: Red Hot Chili Peppers
media_album_name: By The Way [Explicit]
source: Local Speaker
source_list: Local Speaker,Justin?s iPhone
shuffle: true
available: true
last_called: true
friendly_name: Justin's Echo Dot
entity_picture: https://album-art-storage-us.s3.amazonaws.com.....

**Comment by kalkih** [comment]
Thank you
I see what the issue is now, the component seem to set `is_volume_muted` to `true` when volume is `0`, I've not seen that behaviour in other media player components, I think it could cause unwanted side effects.

The volume slider in this card is disabled when the device is muted, just like in core HA.
 
Judging from your video, you can't unmute it either (which would solve the problem)? Possibly because the alexa component treats volume `0` as muted, and as soon as you unmute it, it is muted again since the volume is `0`?

I would recommend opening an issue in the alexa media player repo, feel free to quote me or reference this issue.

Thanks!

**Comment by justin144** [comment]
Will do. Thanks for helping to narrow the issue down!
