### ISSUE TITLE
Styling the player with lovelace-card-mod doesn't work

### ISSUE THREAD

**Issue by burritosoftware** [kalkih/mini-media-player#307]
When styling the mini media player with the card-mod, I can't get the border radius of the card to apply.

Card mod YAML:

```
style: |
  ha-card {
      background-color: var(--primary-background-color);
      border-radius: 15px;
      margin: 10px;
      box-shadow: 
        {% if is_state('sun.sun', 'above_horizon') %}
          -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
        {% else %}
          -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
        {% endif %}   
   }  
```

**Comment by kalkih** [comment]
Try border-radius: 15px !important;

**Comment by burritosoftware** [comment]
@kalkih Nope, no effect unfortunately

**Comment by pejotigrek** [comment]
@burritosoftware I had the same issue. investigating with web-developer tools showed me that there's another object that forces rectangular shape.
try adding this to your styles:

```
    ha-card div.mmp__bg {
      border-radius: 12px !important;
    }
```

looks like **div.mmp__bg** is on top layer and it is forcing the final shape - well at least the visible shape, because other div-objects beneath it still got rounded borders.
