### ISSUE TITLE
Submit translations?

### ISSUE THREAD

**Issue by nagyrobi** [kalkih/mini-media-player#345]
I'd like to translate the buttons "LEAVE" "UNGOUP" "GROUP ALL" etc. to my language. According to the [changelog](https://github.com/kalkih/mini-media-player/blob/06424f033d30ddf9a8bae655e07bb6b71c80ce22/changelog.md#v03) it supports translation but I see these in English only. Where can I contribute with the strings for my language?

**Comment by kalkih** [comment]
Hello,

I'm currently piggybacking on the translations in the Home Assistant frontend, see [translations/frontend](https://github.com/home-assistant/frontend/blob/dev/translations/frontend).
Unfortunately there aren't appropriate ones available for all text elements of the card, that's why some elements aren't translated.

We could potentially add some sort of built-in translation support in the future, where users can provide translations directly in this project. I'll treat this as a feature request.

Thanks!

**Comment by nagyrobi** [comment]
Cool.
A good approach would be maybe to have a resource file containing a dictionaries with strings for the UI elements to be translated. If resource file not present - operate like now.
If current language not found in the resource file - operate like now.
If certain strings are present in the resource take them from there, if not - operate like now.
This way one could add strings specific to this, missing from Home Assistant frontend, or could even override the ones that exist but don't like.

**Comment by kalkih** [comment]
You can now submit translations for your language in the [translations](https://github.com/kalkih/mini-media-player/blob/dev/src/translations.js) file

**Comment by Krocko** [comment]
How can we use this translations?
After the new update, I still have only english text.

**Comment by nagyrobi** [comment]
Can you please add a `label` for "(master)" string too?
