### ISSUE TITLE
Specific service call when clicking power button

### ISSUE THREAD

**Issue by schneekluth** [kalkih/mini-media-player#35]
Please add an option to choose which action shall be triggered when clicking the power button like media_player.media_stop.

**Background:**
I have a tiny cubox i4x4 running LibreElec (Kodi) and this thing is basically always on. You cannot really shut it down so it is idling all the way when not used. I've configured it's default behaviour to reboot Kodi when pressing the power button in the media player config. In mini-media-player it would be nice to tell kodi just to stop the current playing media. Is that possible?

**Comment by kalkih** [comment]
Hey,
Unfortunately I don't think I'm going to add this.
The reason being, I consider this to be a fairly niche use case and I don't want to oversaturate the card with options, since they all add to the complexity and size of the card. 

I think you could solve this with a [Universal media player](https://www.home-assistant.io/components/media_player.universal/), by remapping the on/off commands to `media_player.media_stop`.

You could also fork this project and modify it to suit your needs.

**Comment by schneekluth** [comment]
I understand. Thanks for your reply!
