### ISSUE TITLE
Feature Request: Change icon based on app

### ISSUE THREAD

**Issue by JesseWebDotCom** [kalkih/mini-media-player#354]
It would be great to change the player icon based on app name or id.  For example:
- show Plex icon when watching a movie on plex
- change back to Apple TV icon when no longer watching Plex
- change to Netflix icon when Netflix is playing
- etc

**Comment by kalkih** [comment]
Hello,
Making a generalized solution for this would be hard since different media entities report this differently and we would need to map app names to icons manually.

Using the artwork `default` option you kind of get this, if supported by the card entity.
If that doesn't suit you or if you want specific icons you could achieve this with the help of [config-template-card](https://github.com/iantrich/config-template-card) by templating the icon option.
