### ISSUE TITLE
Feature Request: Limit the card to a specific source

### ISSUE THREAD

**Issue by tringler** [kalkih/mini-media-player#42]
Hello,

thanks for that great card! Would it be possible to implement a feature where I can limit the media player card to a specific source? Maybe with `source: livingroom` as an example.

Let me explain - If you setup Spotify in a multiroom setup you can choose the speaker or speakergroups by the source. What I like to have is a mediaplayer card for each room. In example I like to have a player card for livingroom, bathroom, kitchen, etc. where I can start or stop audio in that room without set the right source every time.

Thanks in Advance, Thomas

**Comment by kalkih** [comment]
Hey!

I'm not sure if this would be possible to achieve in a sensible way without making changes to the backend Spotify HA component.

Do you have any ideas on how this could be implemented?
Thanks.

**Comment by tringler** [comment]
@kalkih Should be very easy I assume - We need to hide the source, which is already implemented and instead of `const source = e.target.getAttribute('value');` at https://github.com/kalkih/mini-media-player/blob/2fc9bec87f7987a271c44a52a93f0928844e8a29/mini-media-player.js#L544 we have that hardcoded option `source: livingroom`, but I'm not too experienced with JS code.

On end-user view all what we would need is that the card has a pre-defined hardcoded source instead of a dropdown-option.

**Comment by kalkih** [comment]
That's not really how the card works. The only thing source does right now is calling the [`media_player.select_source`](https://www.home-assistant.io/components/media_player/#service-media_playerselect_source) service whenever you select an item from the dropdown. It doesn't do anything passively in the background except displaying the current source.

If I understand your request correctly, you want the Spotify component to basically act and display as different media players in the frontend based on which source you specify.

If you think about it, this feature would require a lot more to work properly, if I understand your request correct.

It would need to render and display information based on if the specified source is the active source or not. Basically if the current source on Spotify is "kitchen" and it is playing music you wouldn't want the card that should act as "bedroom" to render as playing and show media information?

It would also require something like calling `media_player.select_source` every time you start media from the card and the source isn't the specified one.

**Comment by tringler** [comment]
mhh I see - To implement the play/stop feature with a hardcoded source would be easy, but the right view will be a big problem, because it's still the same entity which is playing.

What do you think would be the right approach to solve that "problem"?

**Comment by kalkih** [comment]
Frist you would have to add a source option, like `render_source_only` or something similar, where you specify which source to render.

As for rendering the correct information based on source a check could be implemented in the hass setter before the entity is set.
The check could check if `entity.attribute.source` equals the specified source, and if not, modify the entity object or set it to a default object you've specified.
Since the card computes what to render mostly based on the entity object, I think this approach should work fairly well.

https://github.com/kalkih/mini-media-player/blob/2fc9bec87f7987a271c44a52a93f0928844e8a29/mini-media-player.js#L64-L69

Even better would be to create a entity setter where you call the check before setting the entity.

It's an interesting feature and I see some use cases for it, but I won't be adding it to the card, at least not at the moment.
However, you are free to fork this repo and add this feature, and you can always holla at me if you get stuck or need help.

**Comment by tringler** [comment]
Ok - Thanks for clarification and offered help.
