### ISSUE TITLE
Power ON/OFF do not work

### ISSUE THREAD

**Issue by RestOp** [kalkih/mini-media-player#424]
Hello,

- LG TV SmartOS
- 2 x Google Home Mini
- Xiaomi Mi Box S -Android TV

Nowhere works ON\OFF Control. When i push nothing happens.
With standart media player card everything is ok.

Thanks a lot!

**Comment by bluenazgul** [comment]
i wish we would be able to use the "default" Power Button with custom commands like "Logitech Harmony" like it is possible using shortcuts, so we could hide all other shortcuts when device is off

![image](https://user-images.githubusercontent.com/171537/95897158-5efb2800-0d8d-11eb-8f54-9f3d1d4fe7e8.png)

This is my TV with Shortcuts since default ON/OFF is not working

**Comment by cadavre** [comment]
That's strange, but it's happening for me too. Power button only forks for some Inputs selected. I.e. when I switch to Line1 power button doesn't work, but after I select Spotify it start to work.

> With standart media player card everything is ok.

Same here.

**Comment by cadavre** [comment]
OK, found solution with:

toggle_power | boolean | true | v0.8.9 | Set to false to change the power button behaviour to media_player.turn_on/media_player.turn_off.
-- | -- | -- | -- | --

Not sure @kalkih if this should be set to `true` by default. Looks like it breaks more devices than simple `turn_*`.

**Comment by RestOp** [comment]
> Not sure @kalkih if this should be set to `true` by default. Looks like it breaks more devices than simple `turn_*`.

Seems to be a true!
