### ISSUE TITLE
Proper Install Instruction for Newcomeers

### ISSUE THREAD

**Issue by NFCES** [kalkih/mini-media-player#443]
Please could you provide detailed instructions on how to setup you card. I have tried to follow what appears to be very straight forwards set of instructions, but nothing works. I have spent countless hours trying to figure this out and have gotten nowhere. I have no clue if there any prerequisite, your default GutHUb page shows what appears to be three possible ways to install your card. HACS (does not work), Simple install (does not work), and CLI Install (does not work). Under any one of these copying and pasting any of the 'Examples card' code does not work.

If could provide better instructions (e.g. screenshots) for newcomers, it would be appreciated. I am reluctant to sponsor you without such instructions. Sorry I am new to HA and I am still learning but have a substantial dashboard that I am have worked over the past several months and found all my card easy to setup and configure.

Please help and thank you,

**Comment by loic-moriame** [comment]
Since Home Assistant 0.117, you need to add manually ressources for Lovelace Dashboards (dashboard made from the admin panel, not in yaml files)

Go to Configuration > Lovelace Dashboards
![config general](https://user-images.githubusercontent.com/536434/99776924-dc932000-2b11-11eb-9871-2c93d897c739.png)

Then add a new ressource for mini-player: 
![config lovelace dashboard](https://user-images.githubusercontent.com/536434/99776932-def57a00-2b11-11eb-88db-9a721ce45f4c.png)

**Comment by kalkih** [comment]
Thanks for the feedback, I've myself never tried to configure Home Assistant from the UI, so I've no real knowledge on it.

However @theFork submitted a great PR with better instructions on my other repo, we should be able to bring them over. https://github.com/kalkih/mini-graph-card/pull/416

And btw, If you've managed to install other custom card and got them working you should be able to apply the same technique when installing this one.

Closing in favor for #128
