### ISSUE TITLE
Toggle instead of check boxes (grouping speakers) 

### ISSUE THREAD

**Issue by Naviato** [kalkih/mini-media-player#530]
I'm using the sample configuration for grouping speakers and cannot change the toggle buttons to checkboxes. When pressed, the toggle buttons add speakers to the group incrementally and the process takes time since the toggle doesn't change until the items are added to the group. The checkboxes are more efficient since the grouping only takes place after clicking, "group." Is my code wrong?

<img width="510" alt="image" src="https://user-images.githubusercontent.com/85447492/127246983-039770b7-e125-438f-9ade-688b742876cd.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/85447492/127247026-8a7d17cb-15df-452f-9bfb-1bf207e4cc67.png">

**Comment by orestesgaolin** [comment]
Would also love to know that

**Comment by kalkih** [comment]
Hello,
These were actually toggles previously, I believe the reason behind the switch from toggles to checkboxes was because the ha-switch were no longer imported by HA at runtime (hence not consistently available for custom cards).
I didn't want to bundle an additional toggle component with the card so I switched to checkboxes that were available from HA instead.
This might have changed, and we could perhaps have a look at switching back.

**Comment by kalkih** [comment]
So I just checked & the checkbox element is still dynamically imported by Home Assistant, hence not guaranteed to be available to use for custom cards.

We'll stick with the toggles unless this changes in the future.
