### ISSUE TITLE
Uncaught (in promise) /local/custom/mini-media-player.js?v=0.9.8

### ISSUE THREAD

**Issue by TheZoker** [kalkih/mini-media-player#57]
For some reason I get this error since today:
![screenshot_2019 01 15_00h23m13s_002_](https://user-images.githubusercontent.com/1368405/51147789-e71c6880-185b-11e9-80dc-8cf493beec60.png)

Do you have any idea why?

If you need more info, let me know

**Comment by ZinkNotTheMetal** [comment]
I have the exact same problem.

The issue does not show up in iPhone App but does show up on latest version of Chrome (desktop)

**Comment by iantrich** [comment]
@ZinkNotTheMetal you probably still have the cached lit dependencies in the app

**Comment by ZinkNotTheMetal** [comment]
Ah makes sense. Should I change mine to remove the unpkg reference like you did in your change set? or just wait for unpkg to come back up?

**Comment by iantrich** [comment]
@ZinkNotTheMetal your call

**Comment by kalkih** [comment]
You should switch over to the bundle version of the card (check the readme for the updated instructions) where LitElement and other dependencies are bundled in, that way you won't rely on loading dependencies externally.

I'll take a look at @iantrich PR later.

**Comment by ZinkNotTheMetal** [comment]
thanks for the quick response! and this awesome plug-in keep it up!

**Comment by iantrich** [comment]
@kalkih I was using the bundled version and still having the issues 🤷‍♂️

**Comment by TheZoker** [comment]
Me too. Used bundled version

**Comment by kalkih** [comment]
Strange, are you really sure you got the [bundle](https://github.com/kalkih/mini-media-player/releases/tag/v0.9.8)?

Did you rename the file, or why is its name `mini-media-player.js` and not `mini-media-player-bundle.js`, if you've made the name change intentionally and are using custom updater I recommend you to redownload the latest release (bundle) and keep its default name, since custom updater will grab the non bundle version when it updates the card otherwise.

Checked my HA frontend and it does indeed look like unpkg has problems atm, you can see button-card won't load properly but mini media player (bundle) does, since the dependencies are available locally.
<img width="1176" alt="screenshot 2019-01-15 at 01 25 48" src="https://user-images.githubusercontent.com/457678/51150007-cb699000-1864-11e9-9566-7d49c26d0cc1.png">

**Comment by TheZoker** [comment]
Yes I renamed the file, since I had the file reference (without the bundle) before and just wanted to replace the content. I have a custom folder structure, so I'm not sure if I can use custom updater anyway (also custom updater only changes the ui-lovelace.yaml and I'm using the storage version)

**Comment by kalkih** [comment]
I see!
As long as you're not using custom updater, renaming the file is totally fine!
Try grabbing the bundle version, should both load faster and work offline 👍
