### ISSUE TITLE
REWIND & FAST_FORWARD custom buttons 

### ISSUE THREAD

**Issue by jithan10** [kalkih/mini-media-player#591]
Hi I'm attempting to insert two custom buttons to Rewind  back 30 seconds to  or Fast forward 30 seconds but its not working can you help me with this 

type: custom:mini-media-player
group: false
buttons:
  - icon: jump_amount
entity: media_player.enj_room_tv
replace_mute: next
shortcuts:
  columns: 2
  buttons:
    - icon: mdi:rewind
      type: FAST_FORWARD
      option: media_seek
      jump_amount: 30
      REWIND: 30
    - icon: mdi:fast-forward
      option: media_seek
      type: jump_amount
      jump_amount: -30
      FAST_FORWARD: 30

**Comment by kalkih** [comment]
Hello,
I don't know if this has been made easier in HA since the last time I looked into this but, check this issue for a potential solution https://github.com/kalkih/mini-media-player/issues/457.

This is now also a feature available in the card, although not in the shortcut buttons, see https://github.com/kalkih/mini-media-player/pull/547 for more info.
