### ISSUE TITLE
Grouping/Multiroom does not work for a Denon DHT-S516H

### ISSUE THREAD

**Issue by airbone42** [kalkih/mini-media-player#712]
First of all, awesome card, especially that it supports grouping for Denon devices. I have various Denon speaker at home: Heos 7, Heos Sub, Home 150, Heos 5 and DHT-S516H.

All works fine, except that the card doesn't recognize when I group the DHT-S516H as a slave. I have previously created a group using the Heos app, but the toggle for this speaker stays off. I can also see at the entities in HA that it's currently playing, so the connection seems to be fine, just the group feature on this card is off. Also when I want to create a group with the card when selecting this speaker (DHT-S516H) as a slave the toggle can't be switched on. But if this speaker (DHT-S516H) is the master (which unfortunately is not a viable use-case at my home) it can also create the groups easily.

When trying to create the group with the DHT-S516H I get following log message:
`2022-11-14 10:25:07.805 ERROR (MainThread) [homeassistant.components.heos] Failed to group media_player.buro_rechts with ['media_player.wohnzimer_heos']: System error -9 (12)
`

**Comment by kalkih** [comment]
Hey, glad you like the card.

Based on what you describe as well as the error, this seems to be an issue with the [heos integration](https://www.home-assistant.io/integrations/heos/).

Found this https://github.com/home-assistant/core/issues/71425 unresolved issue that seems related, It's closed however,  so I think you'll want to create a new issue over there in order to get support with this.
