### ISSUE TITLE
Sonos Group Management - Ability to uncheck the master

### ISSUE THREAD

**Issue by rgogada** [kalkih/mini-media-player#91]
This is an excellent card as it is. but if you can add the ability to uncheck the master speaker that would be great. You can make it "Default" as in, if no other speaker is checked, it will be checked automatically. 

Current behavior:  the master is always checked irrespective of which room I am in. May be, you are expecting the user to have separate cards for every speaker, but I am trying to getting away with single card for all of my sonos.

New behavior:  When I am not in office (say in bedroom) I can still use the same card by un-checking the office and checking only bedroom. The current setup forces me to play it in office as well no matter which room I am in.

![image](https://user-images.githubusercontent.com/4284896/53691262-d7d08a80-3dc9-11e9-83c9-b972b02324a2.png)

**Comment by kalkih** [comment]
I’m sorry to say this but I won’t be adding this functionality to this card.

The card is built and intended to only control one entity.
The Sonos implementation we got so far works well because the entity provides the basic group information (for that Sonos) we need through its attributes.

This feature would require the card to watch and keep track of all Sonos players, and their group arrangements.

While it’s a great idea I would much rather see this type of functionality in some sort of custom Sonos card. A card that is dedicated to Sonos group arrangement and other Sonos specific features.

**Comment by rgogada** [comment]
thats ok. I see your point. thanks for considering.
