### ISSUE TITLE
Alexa Announcement Feature Request

### ISSUE THREAD

**Issue by 4meuwil** [kalkih/mini-media-player#99]
Is there any way to incorporate an announcement option for alexa?  `type: announcement &  method:all` It would only be used in some situations so it would have to be optional somehow per player entry. for example, i use state-switch cards to target individual echo dots and show, but also have an "ALL" player that targets a speaker group. If i could set that tts config to actually do an announcement that would be awesome.

**Comment by 4meuwil** [comment]
and would need a `target` parameter as well.

**Comment by kalkih** [comment]
Sorry I'm not very familiar with Alexa, does the `tts` option not suit your needs?
The `tts` option will support target(s) for alexa in the next release https://github.com/kalkih/mini-media-player/commit/2b28f62f447f594684d7e89a8d03b6fc60885292.

**Comment by kalkih** [comment]
Just saw this in the custom Alexa media component wiki:

> **TTS** - This is the older media_player.alexa_tts functionality. Alexa will speak using Alexa's Simon says skill and will not sync between devices. This does not work with an Alexa Whole House Audio group (WHA).
**Announce** - This functionality will result in a beep prior to speaking. It can also allow display on Echo Shows/Spots (currently untested). Speech will sync across multiple devices and WHA groups should work.

This card is using tts atm, what if we changed it to announce? do you know if there would be any drawbacks, except potentially the beep in the beginning?

**Comment by kalkih** [comment]
@alandtse Sorry for tagging you, but maybe you can help answer this question.

> This card is using tts atm, what if we changed it to announce? do you know if there would be any drawbacks, except potentially the beep in the beginning?

And while you're here, great development on the component! Makes me wish I had some echo devices 😆

**Comment by 4meuwil** [comment]
The "alexa as a media player" custom component was updated to include making "announcements" in which echo devices play an alert tone before the broadcast as well as putting the message on the echo show screen. That's what i was referring to.

**Comment by 4meuwil** [comment]
i think having the option to choose between tts and announce would be ideal....but I personally do prefer the announce method as the members seem to perk up and listen after the tone....and the display on echo show is nice.

**Comment by alandtse** [comment]
> > This card is using tts atm, what if we changed it to announce? do you know if there would be any drawbacks, except potentially the beep in the beginning?

@kalkih no problem; happy to help.

TTS and announce probably provide similar functionality but is dependent on region support. We haven't done a formal analysis but I think TTS may have broader Amazon rollout, so it's possible some regions may not have a working Announce yet.

Announce is more featureful in that it allows display on Echo Show and Spot devices and in theory will sync the speaking (some users have reported otherwise).  It also handles the Whole House Audio-case where Amazon creates a virtual speaker object you can pass music and other services like Announce to.  

I think it's up to you to determine how it fits into Mini Media Player, but I think users like @4meuwil would prefer to have a parameter to choose which version to use.  Perhaps you can do an alexaannounce or alexatts option if it isn't too hard.

**Comment by kalkih** [comment]
Thank you for the details and input.
As you two suggested, the ability to choose between `tts` and `announce` is probably the right direction then, I'll add it with the next release.

Thanks!

**Comment by kalkih** [comment]
Now available in the latest release through the new `type` option in the [tts](https://github.com/kalkih/mini-media-player#tts-object) option object. Defaults to `tts`.
